config/routes.rb
Rails.application.routes.draw do

  constraints(subdomain: 'heidelbeere') do
    root to: 'subdomain_rentings#index', as: :sub_hunckler
    #get 'simulateur', to: 'subdomain_rentings#simulator', as: :sub_simulateur
    get 'appartement', to: 'subdomain_rentings#renting1', as: :grenier
    get 'studio', to: 'subdomain_rentings#renting2', as: :studio
  end
  constraints(subdomain: 'modenberg') do
    root to: 'subdomain_rentings#index', as: :sub_lindauer
    #get 'simulateur', to: 'subdomain_rentings#simulator', as: :sub_simulateur
    get 'gite', to: 'subdomain_rentings#renting1', as: :gite
  end
  #constraints(subdomain: 'blog') do
  #  root to: 'pages#blog', as: 'blog'
  #end
  resources :blog_posts, path: '/blog/' do
    collection do
      get "actualites", to: "blog_posts#actualites"
      get "ligne-maginot", to: "blog_posts#ligne_maginot"
      get "thermalisme", to: "blog_posts#thermalisme"
      get "tourisme", to: "blog_posts#tourisme"
    end
  end

  #get "/fr/blog/", to: redirect("/blog/")
  #get "/fr/blog/:id", to: redirect("/blog/%{id}")
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    devise_for :users
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    root to: 'pages#home'

    get 'about', to: 'pages#about', as: :about
    get 'contact', to: 'pages#contact', as: :contact
    get 'mentions', to: 'pages#mentions', as: :mentions
    get 'alentours', to: 'pages#alentours', as: :alentours
    get 'simulateur', to: 'pages#simulator', as: :simulateur
    get 'tarifs', to: 'pages#tarifs', as: :tarifs
    get 'cookies', to: 'pages#cookies_infos'
    get 'faq', to: 'pages#faq'
    get 'cgv', to: 'pages#cgv'
    get 'calendar', to: 'subdomain_rentings#calendar', as: :calendar

    get 'taxe-invoice', to: 'pages#taxe_invoice'
    get "taxe_invoice", to: redirect("taxe-invoice")

    post 'result', to: 'pages#result', as: :result
    post 'taxe-facture', to: 'pages#result_invoice'

    resources :holiday_rentings
    resources :commerces do
      member do
        get :orders
      end
      resources :products, only: [ :new, :create, :edit, :update, :destroy ] do
        resources :cart_items do
          collection do
            get :add_to_cart
            get :remove_to_cart
            get :view_cart
          end
        end
      end
    end
    resources :orders, only: [:show, :new, :create]

    get 'order_items/destroy'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :rentings, :path => 'location-vacances' do
      collection do
        get "remove-photo", to: "rentings#remove_photo"
        get "contact", to: "rentings#contact"
        get "contact_send", to: "rentings#contact_send"
        get "locations-chasse", to: "rentings#chasse"
        get "select", to: "rentings#select"         # collection => no restaurant id in URL
        get 'gites-heidelbeere'
        get 'meuble-heidelbeere', to: 'rentings#meuble_heidelbeere', as: :meuble_heidelbeere
        get 'studio-heidelbeere', to: 'rentings#studio_heidelbeere', as: :studio_heidelbeere
      end
    end

    resources :randonnees
    resources :frequent_asks

    scope 'ligne-maginot-alsace' do
      get '/', to: 'ligne_maginots#index', as: :ligne_maginots
      get 'four-a-chaux-lembach', to: 'ligne_maginots#four_a_chaux'
      get 'dambach', to: 'ligne_maginots#dambach'
    end

    resources :marche_noels, :path => "marches-noel"

    scope 'admin' do
      get '/', to: 'owners#index', as: :owner
    end


    resources :landing_pages, :path => '' do
      collection do
        get '/alimentation', to: 'landing_pages#alimentation'
        get '/chateau-fort-alsace', to: 'landing_pages#chateaux_forts'
        get '/lieux-voir-vosges-du-nord', to: 'landing_pages#lieux_vosges'
        get '/cures-thermales', to: 'landing_pages#cures_thermales'
        scope :"cures-thermales" do
          get '/station-thermale-niederbronn', to: 'landing_pages#station_niederbronn'
          get '/station-thermale-niederbronn/location-cure-niederbronn', to: 'landing_pages#location_cure_niederbronn', as: :location_niederbronn
          get 'station-thermale-morsbronn', to: 'landing_pages#station_morsbronn'
          get '/station-thermale-morsbronn/location-cure-morsbronn', to: 'landing_pages#location_cure_morsbronn', as: :location_morsbronn
        end
        get '/ligne-maginot-alsace', to: 'landing_pages#ligne_maginot_alsace'
        #get '/randonnees', to: 'landing_pages#randonnees'
        get '/strasbourg', to: 'landing_pages#strasbourg'
        get '/parcs-attractions', to: 'landing_pages#attraction'
        #get '/marches-noel', to: 'landing_pages#marches_noel'
      end
    end
    resources :articles, :path => ":category"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_blog_categories.html.erb
<aside>
  <nav id="nav-blog">
    <ul class="articles-list none">
      <li><%= link_to 'Actualités', actualites_blog_posts_path %></li>
      <li><%= link_to 'Thermalisme', thermalisme_blog_posts_path %></li>
      <li><%= link_to 'Tourisme', tourisme_blog_posts_path %></li>
      <li><%= link_to 'Ligne Maginot', ligne_maginot_blog_posts_path %></li>
    </ul>
  </nav>
</aside>

app/views/shared/_calendar.html.erb
<%= month_calendar attribute: :start_time, end_attribute: :end_date do |date| %>
  <span class="date" data-day=<%= date %>><%= date.day %></span>
  <% @dates_renting.each do |date_day| %>
    <% if Date.strptime(date_day) == date && DateTime.parse(date_day) > DateTime.now - 1 %>
      <span class="blocked"></span>
    <% end %>
  <% end %>
  <span id="today" data-today=<%= DateTime.now.to_date %>></span>
<% end %>

app/views/shared/_consent_banner.html.erb
<% if cookies.kind_of? ActionDispatch::Cookies::CookieJar %>
  <% if cookies && cookies['cookie_eu_consented'] != 'true' && params[:action] != "cookies_infos" %>
    <div class="cookies-eu fullscreen">
    </div>
    <div class="cookies-eu js-cookies-eu" <%= "dir=rtl" if I18n.exists?('cookies_eu.direction', I18n.locale) && I18n.t("cookies_eu.direction") == "rtl"  %>>
      <span class="cookies-eu-content-holder"><%= t('cookies_eu.cookies_text') %>
      </span>
      <div>
        <span class="cookies-eu-button-holder">
        <button class="cookies-eu-ok js-cookies-eu-ok"> <%= t('cookies_eu.ok') %> </button>
        <% if defined?(link).present? %>
          <a href="<%= link %>" class="cookies-eu-link" target="<%= defined?(target).present? ? target : '' %>"> <%= t('cookies_eu.learn_more') %> </a>
        <% end %>
        </span>
      </div>
    </div>
  <% end %>
<% else %>
  <% raise Exception.new "'cookies' is a reserved Rails class, please rename your method" %>
<% end %>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.querySelector('.alert-dismissible').style.display ='none';"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.querySelector('.alert-dismissible').style.display ='none';"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
  <%= link_to "mentions legales", mentions_path, rel: "nofollow" %>
  <% if locale == :fr && params[:controller] != "blog_posts" %>
    <%= link_to "le blog", blog_posts_path %>
  <% else %>
    <%= link_to "Pays de Niederbronn", root_path %>
  <% end %>
  <!--
    <div class="annuaire">
      <a href="http://www.abc-du-gratuit.com/" target="_blank" title="Annuaire">Annuaire Gratuit</a>
      <a href="https://www.alsace-premier.com" title="Annuaire Alsace" target="_blank">Annuaire Alsace</a>
      <a href="https://annuaire.swcf.fr" title="Annuaire Alsace" target="_blank">Annuaire swcf</a>
    </div>
  -->
</footer>

app/views/shared/_gallery.html.erb
<div class="gg-container" itemprop="photo">
  <div class="gg-box dark" id="heightWidth">
    <% @annonce.photos[0..4].each do |photo| %>
      <%= image_tag photo, class: "visible" %>
      <!--cl_image_tag photo.key, class: "visible"-->
    <% end %>
    <% @annonce.photos.drop(3).each do |photo| %>
      <%= cl_image_tag photo.key, class: "" %>
    <% end %>
  </div>
</div>

app/views/shared/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=GTM-TQZ85P4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
</script>

app/views/shared/_lang_nav.html.erb
<div id="langs">
  <% if I18n.locale == :fr %>
    <%= link_to url_for(locale: :en) do %>
      <%= image_tag "flags/united-kingdom-flag.png", class: "flag", data: { titi: "" } %>
    <% end %>
    <%= link_to url_for(locale: :de) do %>
      <%= image_tag "flags/germany-flag.png", class: "flag", data: { titi: "" } %>
    <% end %>
  <% elsif I18n.locale == :en %>
    <%= link_to url_for(locale: :fr) do %>
      <%= image_tag "flags/france-flag.png", class: "flag", data: { titi: "" } %>
    <% end %>
    <%= link_to url_for(locale: :de) do %>
      <%= image_tag "flags/germany-flag.png", class: "flag", data: { titi: "" } %>
    <% end %>
  <% elsif I18n.locale == :de %>
    <%= link_to url_for(locale: :fr) do %>
      <%= image_tag "flags/france-flag.png", class: "flag", data: { titi: "" } %>
    <% end %>
    <%= link_to url_for(locale: :en) do %>
      <%= image_tag "flags/united-kingdom-flag.png", class: "flag", data: { titi: "" } %>
    <% end %>
  <% end %>
</div>

app/views/shared/_mobile.html.erb
<div id="mobile">
  <%= image_tag "menu-burger.png", class: "mobile-button" %>
</div>

app/views/shared/_nav_blog.html.erb
<nav class="nav blog-links">
  <div>
    <ul>
      <li><%= link_to t('Le Blog'), blog_posts_path, rel: "follow" %></li>
      <li class="mob"><%= link_to 'Actualités', actualites_blog_posts_path %></li>
      <li class="mob"><%= link_to 'Thermalisme', thermalisme_blog_posts_path %></li>
      <li class="mob"><%= link_to 'Tourisme', tourisme_blog_posts_path %></li>
      <li class="mob"><%= link_to 'Ligne Maginot', ligne_maginot_blog_posts_path %></li>
      <li class="mob"><hr></li>
      <li class=""><%= link_to 'Pays Niederbronn', root_path %></li>
    </ul>
  </div>
</nav>

app/views/shared/_navbar-gite.html.erb
<nav class="nav gite">
  <div>
    <%= link_to t('links.home'), root_path, rel: "nofollow" %>
    <%= link_to t('links.se_loger'), rentings_path, rel: "nofollow" %>
    <%= link_to t('links.alentours'), alentours_path, rel: "nofollow" %>
    <%= link_to t('links.contact'), contact_path, rel: "nofollow" %>
    <%= link_to "Calendrier", calendar_path, rel: "nofollow" %>
    <%= link_to "Poster une annonce",new_renting_path, class: "button create", rel: "nofollow" %>
    <%= link_to "Simulateur Taxe", simulateur_path, rel: "nofollow" %>
  </div>
  <%= render 'shared/lang_nav' %>
</nav>

app/views/shared/_navbar.html.erb
<nav class="nav">
  <div>
    <div>
      <ul>
        <li><%= link_to t('links.home'), root_path %></li>
        <li><%= link_to t('links.se_loger'), rentings_path %></li>
        <li><%= link_to t('links.alentours'), alentours_path %></li>
        <li><%= link_to t('links.contact'), contact_path %></li>
        <li><%= link_to t('Blog'), blog_posts_path, rel: "follow" %></li>
        <li class=""><a href="#"><i class="fas fa-user-circle"></i></a>
          <ul class="dropdown">
            <li><%= link_to "Se connecter",  new_user_session_path, rel: "nofollow" %></li>
            <li> <%= link_to "Se déconnecter", destroy_user_session_path, rel: "nofollow" %></li>
            <li><%= link_to 'créer une facture', taxe_invoice_path(), rel: "nofollow" %></li>
            <li><%= link_to "simulateur taxe de sejour", simulateur_path, rel: "nofollow" %></li>
            <li><%= link_to "Poster une annonce",new_renting_path, class: "", rel: "nofollow" %></li>
            <li><%= link_to "Créer un compte",  new_user_registration_path, rel: "nofollow" %></li>
          </ul>

        </li>
      </ul>
    </div>
    <% if params[:controller] != "blog_posts" %>
      <%= render 'shared/lang_nav' %>
    <% else %>
    <% end %>
  </div>
</nav>

app/views/shared/navbar-gite.html.erb
<nav class="nav gite">
  <div>
    <%= link_to t('links.home'), root_path %>
    <%= link_to t('links.se_loger'), holiday_rentings_path %>
    <%= link_to t('links.alentours'), alentours_path %>
    <%= link_to t('links.contact'), contact_path %>
    <%= link_to "Poster une annonce",new_holiday_renting_path, class: "button create" %>
    <%= link_to "Gite", new_holiday_renting_path %>
  </div>
  <%= render 'shared/lang_nav' %>
</nav>