config/routes.rb
Rails.application.routes.draw do

  constraints(subdomain: 'heidelbeere') do
    root to: 'subdomain_rentings#index', as: :sub_hunckler
    #get 'simulateur', to: 'subdomain_rentings#simulator', as: :sub_simulateur
    get 'appartement', to: 'subdomain_rentings#renting1', as: :grenier
    get 'studio', to: 'subdomain_rentings#renting2', as: :studio
  end
  constraints(subdomain: 'modenberg') do
    root to: 'subdomain_rentings#index', as: :sub_lindauer
    #get 'simulateur', to: 'subdomain_rentings#simulator', as: :sub_simulateur
    get 'gite', to: 'subdomain_rentings#renting1', as: :gite
  end
  #constraints(subdomain: 'blog') do
  #  root to: 'pages#blog', as: 'blog'
  #end
  resources :blog_posts, path: '/blog/' do
    collection do
      get "actualites", to: "blog_posts#actualites"
      get "ligne-maginot", to: "blog_posts#ligne_maginot"
      get "thermalisme", to: "blog_posts#thermalisme"
      get "tourisme", to: "blog_posts#tourisme"
    end
  end

  #get "/fr/blog/", to: redirect("/blog/")
  #get "/fr/blog/:id", to: redirect("/blog/%{id}")
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    devise_for :users
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    root to: 'pages#home'

    get 'about', to: 'pages#about', as: :about
    get 'contact', to: 'pages#contact', as: :contact
    get 'mentions', to: 'pages#mentions', as: :mentions
    get 'alentours', to: 'pages#alentours', as: :alentours
    get 'simulateur', to: 'pages#simulator', as: :simulateur
    get 'tarifs', to: 'pages#tarifs', as: :tarifs
    get 'cookies', to: 'pages#cookies_infos'
    get 'faq', to: 'pages#faq'
    get 'cgv', to: 'pages#cgv'
    get 'calendar', to: 'subdomain_rentings#calendar', as: :calendar

    get 'taxe-invoice', to: 'pages#taxe_invoice'
    get "taxe_invoice", to: redirect("taxe-invoice")

    post 'result', to: 'pages#result', as: :result
    post 'taxe-facture', to: 'pages#result_invoice'

    resources :holiday_rentings
    resources :commerces do
      member do
        get :orders
      end
      resources :products, only: [ :new, :create, :edit, :update, :destroy ] do
        resources :cart_items do
          collection do
            get :add_to_cart
            get :remove_to_cart
            get :view_cart
          end
        end
      end
    end
    resources :orders, only: [:show, :new, :create]

    get 'order_items/destroy'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :rentings, :path => 'location-vacances' do
      collection do
        get "remove-photo", to: "rentings#remove_photo"
        get "contact", to: "rentings#contact"
        get "contact_send", to: "rentings#contact_send"
        get "locations-chasse", to: "rentings#chasse"
        get "select", to: "rentings#select"         # collection => no restaurant id in URL
        get 'gites-heidelbeere'
        get 'meuble-heidelbeere', to: 'rentings#meuble_heidelbeere', as: :meuble_heidelbeere
        get 'studio-heidelbeere', to: 'rentings#studio_heidelbeere', as: :studio_heidelbeere
      end
    end

    resources :randonnees
    resources :frequent_asks

    scope 'ligne-maginot-alsace' do
      get '/', to: 'ligne_maginots#index', as: :ligne_maginots
      get 'four-a-chaux-lembach', to: 'ligne_maginots#four_a_chaux'
      get 'dambach', to: 'ligne_maginots#dambach'
    end

    resources :marche_noels, :path => "marches-noel"

    scope 'admin' do
      get '/', to: 'owners#index', as: :owner
    end


    resources :landing_pages, :path => '' do
      collection do
        get '/alimentation', to: 'landing_pages#alimentation'
        get '/chateau-fort-alsace', to: 'landing_pages#chateaux_forts'
        get '/lieux-voir-vosges-du-nord', to: 'landing_pages#lieux_vosges'
        get '/cures-thermales', to: 'landing_pages#cures_thermales'
        scope :"cures-thermales" do
          get '/station-thermale-niederbronn', to: 'landing_pages#station_niederbronn'
          get '/station-thermale-niederbronn/location-cure-niederbronn', to: 'landing_pages#location_cure_niederbronn', as: :location_niederbronn
          get 'station-thermale-morsbronn', to: 'landing_pages#station_morsbronn'
          get '/station-thermale-morsbronn/location-cure-morsbronn', to: 'landing_pages#location_cure_morsbronn', as: :location_morsbronn
        end
        get '/ligne-maginot-alsace', to: 'landing_pages#ligne_maginot_alsace'
        #get '/randonnees', to: 'landing_pages#randonnees'
        get '/strasbourg', to: 'landing_pages#strasbourg'
        get '/parcs-attractions', to: 'landing_pages#attraction'
        #get '/marches-noel', to: 'landing_pages#marches_noel'
      end
    end
    resources :articles, :path => ":category"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/commerce.rb
class Commerce < ApplicationRecord
  belongs_to :user
  has_many :products
  has_many :orders
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/commerces_controller.rb
class CommercesController < ApplicationController
  before_action :cart, only: [:show]
  def index
    @commerces = Commerce.all
  end

  def show
    session.delete(cart)
    @commerce = Commerce.friendly.find(params[:id])
    @products = @commerce.products
    #@order = Order.new
    @cart_item = CartItem.new
    @order = Order.new
    @subtotal = 0
    session[:cart][@commerce.slug].each do |item|
      @subtotal += item["sub_total"]["cents"]
    end
    @subtotal = Money.new(@subtotal)
    #session[:cart]["1"].find {|x| x["name"] == "gâteau à la cannelle"}
  end

  def new
    @commerce = Commerce.new
  end

  def create
    @commerce = Commerce.new(commerce_params)
    @commerce.user = current_user if current_user.present?
    @commerce.save

    redirect_to commerce_path(@commerce)
  end

  def edit
    @commerce = Commerce.friendly.find(params[:id])
  end

  def update
    @commerce = Commerce.friendly.find(params[:id])
    @commerce.update(commerce_params)
  end

  def destroy
  end

  def commerce_params
    params.require(:commerce).permit(:name, :address, :category)
  end

  def cart
    session[:cart] ||= {}
    #session[:cart][@commerce.id.to_s] = {}
    if session[:cart][params[:id]].nil? || session[:cart][params[:id]].empty? || session[:cart][params[:id]].size != Commerce.friendly.find(params[:id]).products.size
      session[:cart][params[:id]]= {}
      arr = []
      keys = ["name", "quantity", "sub_total"]
      Commerce.friendly.find(params[:id]).products.each do |pdt|
        values = [pdt[:name], 0, 0.00]
        x = [keys, values].transpose.to_h
        arr << x
      end
      session[:cart][params[:id]] = arr
      session[:cart][params[:id]].each do |item|
        item["sub_total"] = {"cents"=>0, "currency_iso"=>"EUR"}
      end
    end
    #session[:cart] = session[:cart].inject(:merge)
  end

  def orders
    @commerce = Commerce.friendly.find(params[:id])
    @orders = @commerce.orders
    @order_by_delivery_date = @orders.group_by{|x| x.delivery_date}
  end
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/views/commerces/_cart.html.erb
<ul data-target="form.cart">
  <% items.each do |item| %>
    <% if item["sub_total"]["cents"] != 0 %>
      <li>
          <%= link_to view_cart_commerce_product_cart_items_path(@commerce, @commerce.products.find_by(name: item["name"]), :action_link => "minus"), remote: true do %>
            <i class="fas fa-minus-circle"></i>
          <% end %>
          <p class="price"><%= item["quantity"] %> x <%= item["name"] %> : <%= humanized_money Money.new(item["sub_total"]["cents"]).round(2) %> €</p>
          <%= link_to view_cart_commerce_product_cart_items_path(@commerce, @commerce.products.find_by(name: item["name"]), :action_link => "plus"), remote: true do %>
            <i class="fas fa-plus-circle"></i>
          <% end %>
      </li>
      <% end %>
  <% end %>
</ul>
<p class="price">Total : <%= humanized_money subtotal %><span><%= subtotal.currency.symbol %></span></p>

app/views/commerces/_commerce_content.html.erb
<% products.each do |product| %>
<li class="list-group-item" data-controller="form" data-available=<%=product.availability.select {|k,v| v == true}.keys.to_json %> >
  <div>
  <div>
    <h2><%= product.name.capitalize %></h2>
    <p class="price pricing" data-price="<%= product.price.cents.to_i/100.0 %>">Prix : <%= humanized_money product.price %><span><%= product.price.currency.symbol %></span></p>
    <p class="description"><%= product.description %></p>

    <div class="availabilities">
      <h3>Le produit est disponible le :</h3>
      <ul>
        <% ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche" ].each do |day| %>
          <li class="available-day <%= product.availability[day] %>"><%= day%></li>
        <% end %>
      </ul>
    </div>
    <%= simple_form_for( @cart_item, :url => view_cart_commerce_product_cart_items_path(@commerce, product), :method => :get, remote: true) do |f| %>

  </div>

  <div class="visuel">
    <%= image_tag product.photo, width:150 if product.photo.attached? %>
    <div class="qty-control" data-form-qty-value=<%= session[:cart][@commerce.slug].find {|x| x["name"] == product.name}["quantity"] %> >
      <a href="#" id="minus" data-action="click->form#linkDisabled"><i class="fas fa-minus-circle"></i></a>
      <%= f.input :quantity, label: false, input_html: {value: 0, size: 3} %>
      <a href="#" id="plus" data-action="click->form#linkDisabled"><i class="fas fa-plus-circle"></i></a>
    </div>
    <p class="price"><span class="sumproduct" data-form-target="sumproduct">0.00</span><span><%= product.price.currency.symbol %></span></p>
  </div>
  </div>
  <div class="send-product">
    <%= f.submit class: "btn btn-green beige auto sweet-alert-demo", value: "Ajouter au panier" %>
  </div>

    <% end %>
  <span class="unavailable">produit indisponible</span>
</li>
<% end %>

app/views/commerces/_form.html.erb
<%= simple_form_for @commerce do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :category %>
  <%= f.input :category, :collection => ["boulangerie", "restaurant"], :prompt => "Choisir une catégorie de commerce", label: false %>
  <%= f.submit %>
<% end %>

app/views/commerces/create.html.erb
<h1>Commerces#create</h1>
<p>Find me in app/views/commerces/create.html.erb</p>

app/views/commerces/destroy.html.erb
<h1>Commerces#destroy</h1>
<p>Find me in app/views/commerces/destroy.html.erb</p>

app/views/commerces/edit.html.erb
<h1>Commerces#edit</h1>
<p>Find me in app/views/commerces/edit.html.erb</p>

<%= render 'form' %>

app/views/commerces/index.html.erb
<h1>Commerces#index</h1>
<p>Find me in app/views/commerces/index.html.erb</p>
<ul>
  <% @commerces.each do |commerce| %>
    <%= link_to commerce.name, commerce_path(commerce) %>
  <% end %>
</ul>
<%= session[:cart] %>

app/views/commerces/new.html.erb
<h1>Commerces#new</h1>
<p>Find me in app/views/commerces/new.html.erb</p>
<%= render "form" %>

app/views/commerces/orders.html.erb
<main>
  <article class="article">
    <h1>Commandes</h1>
    <h2>Commerce : <%= @commerce.name %></h2>

    <table>
        <thead>
          <tr>
              <th colspan="">Date de livraison</th>
              <th colspan="">Date de commande</th>
              <th colspan="">Commande</th>
              <th colspan="">Montant</th>
              <th colspan="">Nom</th>
              <th colspan="">Prénom</th>
              <th colspan="">Tel</th>
              <th colspan="">Email</th>
          </tr>
        </thead>
        <tbody>
          <% @order_by_delivery_date.keys.compact.sort.each do |key| %>
            <% @order_by_delivery_date[key].each do |order| %>
              <tr>
                  <td><%= order.delivery_date %></td>
                  <td><%= order.created_at %></td>
                  <td>
                    <ul>
                      <% order.cart_items.each do |item| %>
                        <li><%= item.quantity %> x <%= item.product.name %></li>
                      <% end %>
                    </ul>
                  </td>
                  <td><%= order.amount %><%= order.amount.currency.symbol %></td>
                  <td><%= order.last_name %></td>
                  <td><%= order.first_name %></td>
                  <td><%= order.tel %></td>
                  <td><%= order.email %></td>
              </tr>
            <% end %>
            <tr style="height: 1em;">
            </tr>
          <% end %>
        </tbody>
    </table>
  </article>
</main>

app/views/commerces/show.html.erb
<main id="commerce">
  <article>
    <header>
      <div>
        <h1><%= @commerce.name %></h1>
        <!--
          <div>
            <div>
              <a href=""><i class="fas fa-phone"><p>Appeler</p></i></a>
            </div>
            <div>
              <a href=""><i class="fas fa-map-marker-alt"><p>Lancer l'itinéraire</p></i></a>
            </div>
          </div>
        -->
      </div>
    </header>
    <%= link_to "Commerces", commerces_path %>
    <%= link_to "Nouveau Produit",new_commerce_product_path(@commerce) %>
    <%= link_to "Commandes", orders_commerce_path(@commerce) %>

      <section class="flex" data-controller="form" data-content-loader-url="<%= request.path %>" >
        <div>
          <div class="dates-select">
          <h2>Chosir une date de commande :</h2>
          <input data-controller="form" data-action="input->form#dateInput" data-form-target="dateinput" id="date" type="date" value=<%= DateTime.now.next_day.strftime("%Y-%m-%d") %> required="required" >
          </div>
          <div>
            <div class="tabs">

            <input type="radio" name="tabs" id="tab1" checked="checked">
            <label for="tab1">Tous</label>
            <div class="tab">
              <ul class="list-group">
                <%= render partial: "commerce_content", locals: {products: @commerce.products} %>
              </ul>
            </div>

            <input type="radio" name="tabs" id="tab2">
            <label for="tab2">Pain</label>
            <div class="tab">
              <ul class="list-group">
                <%= render partial: "commerce_content", locals: {products: @commerce.products.where(category:"pain")} %>
              </ul>
            </div>

            <input type="radio" name="tabs" id="tab3">
            <label for="tab3">Viennoiserie</label>
            <div class="tab">
              <ul class="list-group">
                <%= render partial: "commerce_content", locals: {products: @commerce.products.where(category:"viennoiserie")} %>
              </ul>
            </div>

            <input type="radio" name="tabs" id="tab4">
            <label for="tab4">Pâtisserie</label>
            <div class="tab">
              <ul class="list-group">
                <%= render partial: "commerce_content", locals: {products: @commerce.products.where(category:"pâtisserie")} %>
              </ul>
            </div>
          </div>
          </div>
        </div>


        <div class="cart" data-controller="form">
          <h2 class="panier" data-action="click->form#deploy">Mon panier</h2>
          <aside class="" data-form-target="todeploy">
            <div>

            <div id="insert-cart">
              <%= render partial: "cart", locals: {items: session[:cart][@commerce.slug], subtotal: @subtotal} %>
            </div>
            <hr>
            <h2>Mes coordonnées</h2>
            <p id="deliverydate">Commande pour : <%= l((Time.now + 2.day),format: "%A %e %B %Y")  %></p>
            <%= simple_form_for @order do |f| %>
              <%= hidden_field_tag 'commerce_id', @commerce.slug %>
              <%= hidden_field_tag :delivery_date, input_html: {value: Time.now + 2.day } %>
              <%= f.input :last_name, placeholder: "Nom*", label: false, input_html: { "data-form-target" => "content" }, required:true %>
               <%= f.input :first_name, placeholder: "Prénom*", label: false, input_html: { "data-form-target" => "content" }, required:true %>
              <%= f.input :tel, placeholder: "Tel*", label: false, input_html: { "data-form-target" => "content" }, required:true %>
              <%= f.input :email, placeholder: "Email", label: false, input_html: {} %>
              <%= f.input :rgpd, label:"J'accepte que mes coordonnées soient utilisées dans le cadre de ma commande. Ces informations ne seront pas conservées et ne serviront qu'à répondre à votre demande.",:input_html => { :checked => "" }, required:true %>
              <br>
              <%= f.submit 'Envoyer la commande', class: 'btn btn-green beige auto', data: { action: "form#submitForm" } %>
            <% end %>
            </div>
          </aside>
        </div>

      </section>
  </article>
</main>

<%= javascript_pack_tag "sweetalert" %>
<script type="text/javascript">
  (function()
    {
      if( window.localStorage )
      {
        if( !localStorage.getItem('firstLoad') )
        {
          localStorage['firstLoad'] = true;
          window.location.reload();
        }
        else
          localStorage.removeItem('firstLoad');
      }
    })();
</script>

app/views/commerces/update.html.erb
<h1>Commerces#update</h1>
<p>Find me in app/views/commerces/update.html.erb</p>