config/routes.rb
Rails.application.routes.draw do

  constraints(subdomain: 'heidelbeere') do
    root to: 'subdomain_rentings#index', as: :sub_hunckler
    #get 'simulateur', to: 'subdomain_rentings#simulator', as: :sub_simulateur
    get 'appartement', to: 'subdomain_rentings#renting1', as: :grenier
    get 'studio', to: 'subdomain_rentings#renting2', as: :studio
  end
  constraints(subdomain: 'modenberg') do
    root to: 'subdomain_rentings#index', as: :sub_lindauer
    #get 'simulateur', to: 'subdomain_rentings#simulator', as: :sub_simulateur
    get 'gite', to: 'subdomain_rentings#renting1', as: :gite
  end
  #constraints(subdomain: 'blog') do
  #  root to: 'pages#blog', as: 'blog'
  #end
  resources :blog_posts, path: '/blog/' do
    collection do
      get "actualites", to: "blog_posts#actualites"
      get "ligne-maginot", to: "blog_posts#ligne_maginot"
      get "thermalisme", to: "blog_posts#thermalisme"
      get "tourisme", to: "blog_posts#tourisme"
    end
  end

  #get "/fr/blog/", to: redirect("/blog/")
  #get "/fr/blog/:id", to: redirect("/blog/%{id}")
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    devise_for :users
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    root to: 'pages#home'

    get 'about', to: 'pages#about', as: :about
    get 'contact', to: 'pages#contact', as: :contact
    get 'mentions', to: 'pages#mentions', as: :mentions
    get 'alentours', to: 'pages#alentours', as: :alentours
    get 'simulateur', to: 'pages#simulator', as: :simulateur
    get 'tarifs', to: 'pages#tarifs', as: :tarifs
    get 'cookies', to: 'pages#cookies_infos'
    get 'faq', to: 'pages#faq'
    get 'cgv', to: 'pages#cgv'
    get 'calendar', to: 'subdomain_rentings#calendar', as: :calendar

    get 'taxe-invoice', to: 'pages#taxe_invoice'
    get "taxe_invoice", to: redirect("taxe-invoice")

    post 'result', to: 'pages#result', as: :result
    post 'taxe-facture', to: 'pages#result_invoice'

    resources :holiday_rentings
    resources :commerces do
      member do
        get :orders
      end
      resources :products, only: [ :new, :create, :edit, :update, :destroy ] do
        resources :cart_items do
          collection do
            get :add_to_cart
            get :remove_to_cart
            get :view_cart
          end
        end
      end
    end
    resources :orders, only: [:show, :new, :create]

    get 'order_items/destroy'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :rentings, :path => 'location-vacances' do
      collection do
        get "remove-photo", to: "rentings#remove_photo"
        get "contact", to: "rentings#contact"
        get "contact_send", to: "rentings#contact_send"
        get "locations-chasse", to: "rentings#chasse"
        get "select", to: "rentings#select"         # collection => no restaurant id in URL
        get 'gites-heidelbeere'
        get 'meuble-heidelbeere', to: 'rentings#meuble_heidelbeere', as: :meuble_heidelbeere
        get 'studio-heidelbeere', to: 'rentings#studio_heidelbeere', as: :studio_heidelbeere
      end
    end

    resources :randonnees
    resources :frequent_asks

    scope 'ligne-maginot-alsace' do
      get '/', to: 'ligne_maginots#index', as: :ligne_maginots
      get 'four-a-chaux-lembach', to: 'ligne_maginots#four_a_chaux'
      get 'dambach', to: 'ligne_maginots#dambach'
    end

    resources :marche_noels, :path => "marches-noel"

    scope 'admin' do
      get '/', to: 'owners#index', as: :owner
    end


    resources :landing_pages, :path => '' do
      collection do
        get '/alimentation', to: 'landing_pages#alimentation'
        get '/chateau-fort-alsace', to: 'landing_pages#chateaux_forts'
        get '/lieux-voir-vosges-du-nord', to: 'landing_pages#lieux_vosges'
        get '/cures-thermales', to: 'landing_pages#cures_thermales'
        scope :"cures-thermales" do
          get '/station-thermale-niederbronn', to: 'landing_pages#station_niederbronn'
          get '/station-thermale-niederbronn/location-cure-niederbronn', to: 'landing_pages#location_cure_niederbronn', as: :location_niederbronn
          get 'station-thermale-morsbronn', to: 'landing_pages#station_morsbronn'
          get '/station-thermale-morsbronn/location-cure-morsbronn', to: 'landing_pages#location_cure_morsbronn', as: :location_morsbronn
        end
        get '/ligne-maginot-alsace', to: 'landing_pages#ligne_maginot_alsace'
        #get '/randonnees', to: 'landing_pages#randonnees'
        get '/strasbourg', to: 'landing_pages#strasbourg'
        get '/parcs-attractions', to: 'landing_pages#attraction'
        #get '/marches-noel', to: 'landing_pages#marches_noel'
      end
    end
    resources :articles, :path => ":category"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/marche_noel.rb
class MarcheNoel < HolidayRenting
  after_validation :set_category, only: [:create]

  private
  def set_category
    self.category = "marche"
  end
end

app/controllers/marche_noels_controller.rb
class MarcheNoelsController < ApplicationController

  def index
    set_meta_tags title: "Marchés de noel en Alsace",
                description: "les marchés de noel dans l'ensemble de l'Alsace",
                canonical: "https://www.paysniederbronn.fr/fr/marches-noel"
    @marches = MarcheNoel.all.where(category: "marche").order(:titre)
  end

  def new
  end

  def create
  end

  def show
    @marche_noel = MarcheNoel.find(params[:id])
    set_meta_tags noindex: true
  end

  def edit
  end

  def update
  end
end

app/helpers/marche_noels_helper.rb
module MarcheNoelsHelper
end

app/views/marche_noels/create.html.erb
<h1>MarcheNoels#create</h1>
<p>Find me in app/views/marche_noels/create.html.erb</p>

app/views/marche_noels/edit.html.erb
<h1>MarcheNoels#edit</h1>
<p>Find me in app/views/marche_noels/edit.html.erb</p>

app/views/marche_noels/index.html.erb
<main>
  <article class="article">
    <section>
      <h1>Marchés de Noël en Alsace</h1>
      <p>Remontant au XIVème siècle, les <strong>marchés de Noël débutèrent en Alsace</strong> et en Allemagne sous le nom de "Marché de Saint Nicolas". L'appellation évolua progressivement en "Christkindelsmärik" soit le marché de l'enfant Christ.<br>
      Parmi les marchés de noël les plus anciens connus, on retrouve le marché de noël de Strasbourg qui date de 1570 et celui de Nuremberg(Allemagne) qui lui date de 1628.<br>
      Dès 1990, un regain de popularité survint autour de cet événement avec la création dans de nombreuses villes d'Europe de leur propre <strong>marché de Noël</strong>.
      <br><br>
      Aujourd’hui encore, les <strong>marchés de noël</strong> sont surtout présent en Alsace et en Allemagne, on citera par exemple le marché de noël de Strasbourg qui avec ses nombreux chalets est devenu « Capitale de Noël » ou encore les marchés de Colmar, Eguisheim et Kaysersberg qui attirent chaque année des milliers de visiteurs pour y faire découvrir l’artisanat local, les traditions alsaciennes et pour y déguster un bon vin chaud.
      </p>
    </section>
    <section>
      <h2>La liste des marchés de Noël en Alsace</h2>
      <ul class="articles-list">
        <% @marches.each do |market| %>
          <%= link_to marche_noel_path(market) do %>
            <li><h3>Marché de <%= market.titre.capitalize %></h3><p><%= market.summary %></p></li>
          <% end %>
        <% end %>
      </ul>
    </section>
  </article>
</main>

app/views/marche_noels/new.html.erb
<h1>MarcheNoels#new</h1>
<p>Find me in app/views/marche_noels/new.html.erb</p>

app/views/marche_noels/show.html.erb
<h1>Marché de Noël de <%= @marche_noel.titre.capitalize %></h1>
<%= link_to "Les marchés de noël en Alsace", marche_noels_path %>

app/views/marche_noels/update.html.erb
<h1>MarcheNoels#update</h1>
<p>Find me in app/views/marche_noels/update.html.erb</p>